const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Plugins.Keyboard,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.LOS,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pathfinding.Acts.AddObstacle,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.LOS.Acts.SetRange,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.NextPrevLayout
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{PlanoDeFundoEmBlocos: 0},
	{labirinto1: 0},
	{"8Direções": 0},
	{MagoVermelh: 0},
	{Teclado: 0},
	{ExploradorDeRotas: 0},
	{CampoDeVisão: 0},
	{fireballVima: 0},
	{diamante: 0},
	{labirinto2: 0},
	{labirinto3: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{vidas: 0},
	{vida: 0},
	{magoVermelho: 0},
	{MazeRush: 0},
	{Texto: 0},
	{Texto2: 0},
	{Texto3: 0},
	{blocoDeVolta: 0},
	{play: 0},
	{sobre: 0},
	{Sprite5: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Mouse: 0},
	{avante1: 0},
	{voltar: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{magoQueimado: 0},
	{inicio: 0},
	{reiniciar: 0},
	{Texto4: 0},
	{Texto5: 0},
	{proximo: 0},
	{inicio2: 0},
	{vida2: 0},
	{vida3: 0},
	{Áudio: 0},
	{Sprite: 0},
	{vidas2: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	labirinto1: class extends self.ISpriteInstance {},
	MagoVermelh: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	fireballVima: class extends self.ISpriteInstance {},
	diamante: class extends self.ISpriteInstance {},
	labirinto2: class extends self.ISpriteInstance {},
	labirinto3: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	vida: class extends self.ISpriteInstance {},
	magoVermelho: class extends self.ISpriteInstance {},
	MazeRush: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	blocoDeVolta: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	sobre: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	avante1: class extends self.ISpriteInstance {},
	voltar: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	magoQueimado: class extends self.ISpriteInstance {},
	inicio: class extends self.ISpriteInstance {},
	reiniciar: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	proximo: class extends self.ISpriteInstance {},
	inicio2: class extends self.ISpriteInstance {},
	vida2: class extends self.ISpriteInstance {},
	vida3: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {}
}